/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.UserDao;
import Enity.User;
import ThuVien.Auth;
import ThuVien.DialogHelper;
import TienIch.Validator;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author trinh
 */
public class ForgetPWForm extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPWForm
     */
    UserDao daoUser = new UserDao();
    Timer progessOTP;
    int timeOTP = 60;
    String otp;

    public ForgetPWForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.blue);
        panelOTP.setVisible(false);
        lblPW.setVisible(false);
        txtNotifice.setVisible(false);
        lblConfirmPW.setVisible(false);
        lblPW.setVisible(false);
        txtConfirmPW.setVisible(false);
        txtPW.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmailFormReset = new javax.swing.JTextField();
        panelOTP = new javax.swing.JPanel();
        txtOTP = new javax.swing.JTextField();
        btnResetPW = new javax.swing.JButton();
        txtInfo = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        txtNotifice = new javax.swing.JLabel();
        txtConfirmPW = new javax.swing.JTextField();
        lblConfirmPW = new javax.swing.JLabel();
        txtPW = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txtEmailFormReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtEmailFormReset, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEmailFormReset, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        panelOTP.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter OTP"));

        txtOTP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelOTPLayout = new javax.swing.GroupLayout(panelOTP);
        panelOTP.setLayout(panelOTPLayout);
        panelOTPLayout.setHorizontalGroup(
            panelOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOTPLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOTPLayout.setVerticalGroup(
            panelOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOTP, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnResetPW.setBackground(new java.awt.Color(51, 51, 51));
        btnResetPW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResetPW.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPW.setText("Send OTP");
        btnResetPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPWActionPerformed(evt);
            }
        });

        txtInfo.setBackground(new java.awt.Color(51, 51, 51));
        txtInfo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInfo.setText("RESET YOUR ACCOUNT");
        txtInfo.setOpaque(true);
        txtInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInfoMouseClicked(evt);
            }
        });

        lblPW.setBackground(new java.awt.Color(204, 204, 204));
        lblPW.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPW.setForeground(new java.awt.Color(255, 255, 255));
        lblPW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPW.setText("Password");
        lblPW.setOpaque(true);
        lblPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPWMouseClicked(evt);
            }
        });

        txtNotifice.setBackground(new java.awt.Color(204, 204, 204));
        txtNotifice.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtNotifice.setForeground(new java.awt.Color(0, 204, 51));
        txtNotifice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNotifice.setText("Otp has been sent to your email");
        txtNotifice.setOpaque(true);
        txtNotifice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNotificeMouseClicked(evt);
            }
        });

        lblConfirmPW.setBackground(new java.awt.Color(204, 204, 204));
        lblConfirmPW.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblConfirmPW.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmPW.setText("Comfirm");
        lblConfirmPW.setOpaque(true);
        lblConfirmPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmPWMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnResetPW, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNotifice, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelOTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPW, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPW))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotifice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPW)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPW, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnResetPW, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInfoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInfoMouseClicked

    private void btnResetPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPWActionPerformed
        // TODO add your handling code here:

        if (btnResetPW.getText().equals("Reset")) {

            if (txtPW.getText().trim().isEmpty() || txtConfirmPW.getText().trim().isEmpty()) {
                DialogHelper.alert(null, "Fill full infomation!!!");
                return;
            }

            if (!txtPW.getText().trim().equals(txtConfirmPW.getText().trim())) {
                DialogHelper.alert(null, "Password no matching!!!");
                return;
            }

            try {
                daoUser.changePassword(txtEmailFormReset.getText().trim(), Auth.md5(txtPW.getText().trim()));
                DialogHelper.alert(null, "Reset Successfully !!!");
                this.dispose();
            } catch (Exception e) {
                System.out.println(e);
                DialogHelper.alert(null, "Reset ERRORS");
            }

        }

        if (btnResetPW.getText().equals("VERIFY")) {
            String otpUserEnter = txtOTP.getText().trim();
            if (otpUserEnter.equals(otp)) {
                progessOTP.stop();
                lblPW.setText("Password :");
                lblConfirmPW.setVisible(true);
                lblPW.setVisible(true);
                txtConfirmPW.setVisible(true);
                txtPW.setVisible(true);
                panelOTP.setVisible(false);
                btnResetPW.setText("Reset");
                txtNotifice.setVisible(false);
            }else{
                txtNotifice.setText("OTP Not True");
                txtNotifice.setForeground(Color.red);
            }
            return;
        }

        User checkExits = daoUser.selectByEmail(txtEmailFormReset.getText().trim());
        if (txtEmailFormReset.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter your email !!!");
            return;
        }

        if (checkExits == null) {
            JOptionPane.showMessageDialog(null, "Your email no exits in app !!!");
            return;
        }
        jPanel1.setEnabled(false);
        timeOTP = 60;
        panelOTP.setVisible(true);
        lblPW.setVisible(true);
        txtNotifice.setVisible(true);
        btnResetPW.setText("VERIFY");
        otp = "" + Math.round(Math.random() * 9) + Math.round(Math.random() * 9) + Math.round(Math.random() * 9) + Math.round(Math.random() * 9) + Math.round(Math.random() * 9) + Math.round(Math.random() * 9);

        /// send otp 
        try {
            Session session;
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com"); // Replace with your SMTP server
            p.put("mail.smtp.port", 587); // Replace with the appropriate port for your SMTP server

            // EMAIL ADMIN
            String userEmail = "freedb2004@gmail.com";
            String passwordEmail = "ajji ywjl ptqk lfld";
            // Create a session with authentication
            session = Session.getInstance(p, new javax.mail.Authenticator() {
                protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                    return new javax.mail.PasswordAuthentication(userEmail, passwordEmail);
                }
            });
            // Create a message
            Message message = new MimeMessage(session);

            // Set the sender's email address
            message.setFrom(new InternetAddress(userEmail));

            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(txtEmailFormReset.getText().trim()));
            // Set the subject of the email
            message.setSubject("OTP PASSWORD PROJECT");
            message.setText(otp);
            // Set the content of the email
            // Send the message
            Transport.send(message);
        } catch (Exception e) {
            System.out.println(e);
        }
        progessOTP = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timeOTP--;
                if (timeOTP < 0) {
                    panelOTP.setVisible(false);
                    lblPW.setVisible(false);
                    txtNotifice.setVisible(false);
                    jPanel1.setEnabled(true);
                    btnResetPW.setText("SEND OTP");
                    progessOTP.stop();
                }
                lblPW.setText(timeOTP + "S");
            }
        });
        progessOTP.start();

    }//GEN-LAST:event_btnResetPWActionPerformed

    private void lblPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPWMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPWMouseClicked

    private void txtNotificeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotificeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotificeMouseClicked

    private void lblConfirmPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmPWMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConfirmPWMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPWForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPWForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPWForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPWForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPWForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetPW;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmPW;
    private javax.swing.JLabel lblPW;
    private javax.swing.JPanel panelOTP;
    private javax.swing.JTextField txtConfirmPW;
    private javax.swing.JTextField txtEmailFormReset;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtNotifice;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JTextField txtPW;
    // End of variables declaration//GEN-END:variables
}
